const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.join(__dirname,'dist'),dataDir=path.resolve(process.env.DATA_DIR||path.join(__dirname,'.runtime'));fs.mkdirSync(dataDir,{recursive:true});const store=path.join(dataDir,'rooms.json');
let rooms={};if(fs.existsSync(store)){try{rooms=JSON.parse(fs.readFileSync(store,'utf8'))}catch{throw Error('Cannot read room store; refusing to overwrite it')}}
const clients=new Map(),limits=new Map(),counts=[4,5,3,6,5,3],hash=t=>crypto.createHash('sha256').update(t).digest('hex');
function fresh(){return {stage:0,step:0,cursor:0,focus:0,turn:0,done:{},reveal:false,showPeers:false,pairChosen:false,attempt:0,timer:{remaining:3600,startedAt:null}}}
function save(){const tmp=store+'.tmp';fs.writeFileSync(tmp,JSON.stringify(rooms),{mode:0o600});fs.renameSync(tmp,store)}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function fail(status,message){const e=Error(message);e.status=status;throw e}
function rate(req,bucket,max,window=60000){const key=req.socket.remoteAddress+':'+bucket,now=Date.now(),times=(limits.get(key)||[]).filter(t=>now-t<window);if(times.length>=max)fail(429,'Слишком много попыток. Подождите и попробуйте снова.');times.push(now);limits.set(key,times)}
function token(){return crypto.randomBytes(32).toString('base64url')}
function code(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let out;do{out=Array.from(crypto.randomBytes(8),b=>alphabet[b%alphabet.length]).join('')}while(rooms[out]);return out}
function authenticate(req){const value=req.headers.authorization||'';if(!value.startsWith('Bearer ')||value.length>150)fail(401,'Доступ не подтверждён.');const h=hash(value.slice(7));for(const r of Object.values(rooms)){const m=r.members.find(v=>v.tokenHash===h);if(m){if(Date.now()>r.expiresAt)fail(410,'Комната истекла. Создайте новую.');return {r,m,h}}}fail(401,'Недействительный доступ к комнате.')}
function current(r){const l=r.lesson;return `${l.stage}-${l.step}-${l.cursor}`}
function snapshot(r,m){return {code:r.code,revision:r.revision,serverTime:Date.now(),lesson:r.lesson,me:publicMember(m),members:r.members.map(publicMember),answers:r.answers.filter(a=>m.role==='teacher'||a.memberId===m.id||(r.lesson.showPeers&&a.activity===current(r)&&a.attempt===r.lesson.attempt))}}
function publicMember(m){return {id:m.id,name:m.name,avatar:m.avatar,role:m.role,slot:m.slot,connected:!!clients.get(m.tokenHash)?.size}}
function send(res,data){if(!res.writableEnded)res.write('data: '+JSON.stringify(data)+'\n\n')}
function broadcast(r,persist=true){r.revision++;if(persist)save();for(const m of r.members)for(const res of clients.get(m.tokenHash)||[])send(res,snapshot(r,m))}
function newMember(name,role,slot,avatar=0){const access=token();return {access,member:{id:crypto.randomUUID(),tokenHash:hash(access),name,role,slot,avatar}}}
function name(value){if(typeof value!=='string'||!value.trim()||value.trim().length>32)fail(400,'Введите имя: от 1 до 32 символов.');return value.trim()}
function teacher(m){if(m.role!=='teacher')fail(403,'Это действие доступно только преподавателю.')}
async function body(req){let text='';for await(const chunk of req){text+=chunk;if(Buffer.byteLength(text)>16000)fail(413,'Слишком большой запрос.')}try{return JSON.parse(text||'{}')}catch{fail(400,'Некорректный запрос.')}}
function remaining(timer){return timer.startedAt?Math.max(0,timer.remaining-Math.floor((Date.now()-timer.startedAt)/1000)):timer.remaining}
function prune(){let changed=false;for(const [c,r] of Object.entries(rooms))if(Date.now()>r.expiresAt){delete rooms[c];changed=true;for(const m of r.members)for(const res of clients.get(m.tokenHash)||[])res.end()}if(changed)save();for(const [k,v] of limits)if(v.every(t=>Date.now()-t>600000))limits.delete(k)}
setInterval(prune,60000).unref();
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){
 if(req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)fail(403,'Запрос должен идти с адреса сайта.');
 if(url.pathname==='/api/health'){json(res,200,{ok:true,backend:'Node + SSE',roomLimit:2});return}
 if(url.pathname==='/api/events'){const {r,m,h}=authenticate(req);if(req.method!=='GET')fail(405,'Метод не разрешён.');if((clients.get(h)?.size||0)>=4)fail(429,'Закройте лишние вкладки комнаты.');res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-store','Connection':'keep-alive','X-Accel-Buffering':'no'});if(!clients.has(h))clients.set(h,new Set());clients.get(h).add(res);broadcast(r,false);const pulse=setInterval(()=>res.write(': heartbeat\n\n'),10000);res.on('close',()=>{clearInterval(pulse);clients.get(h)?.delete(res);if(!clients.get(h)?.size)clients.delete(h);broadcast(r,false)});return}
 if(req.method!=='POST')fail(405,'Метод не разрешён.');const b=await body(req);
 if(url.pathname==='/api/create'){rate(req,'create',4);prune();if(Object.keys(rooms).length>=200)fail(503,'Сервер занят. Повторите позже.');const {access,member}=newMember(name(b.name||'Sonya'),'teacher',-1),c=code(),r={code:c,members:[member],lesson:fresh(),answers:[],revision:1,expiresAt:Date.now()+86400000};rooms[c]=r;save();json(res,201,{credential:{token:access,code:c},room:snapshot(r,member)});return}
 if(url.pathname==='/api/join'){rate(req,'join',12,600000);const c=String(b.code||'').replace(/\s/g,'').toUpperCase();const r=rooms[c];if(!r||Date.now()>r.expiresAt)fail(404,'Комната не найдена. Проверьте код у преподавателя.');const students=r.members.filter(m=>m.role==='student');if(students.length>=2)fail(409,'В комнате уже две ученицы. Вернитесь из браузера, где вы вошли раньше.');const avatar=Number.isInteger(b.avatar)&&b.avatar>=0&&b.avatar<4?b.avatar:0;const used=students.map(m=>m.avatar);const chosen=used.includes(avatar)?[0,1,2,3].find(v=>!used.includes(v)):avatar;const {access,member}=newMember(name(b.name),'student',[0,1].find(slot=>!students.some(m=>m.slot===slot)),chosen);r.members.push(member);broadcast(r);json(res,201,{credential:{token:access,code:c},room:snapshot(r,member)});return}
 const {r,m}=authenticate(req);rate(req,'member:'+m.id,120);const l=r.lesson;
 if(url.pathname==='/api/state'){teacher(m);const p=b.patch||{};if(p.stage!==undefined&&(!Number.isInteger(p.stage)||p.stage<0||p.stage>5))fail(400,'Неизвестный этап.');const stage=p.stage??l.stage;if(p.step!==undefined&&(!Number.isInteger(p.step)||p.step<0||p.step>=counts[stage]))fail(400,'Неизвестное упражнение.');for(const field of ['cursor','focus','turn'])if(p[field]!==undefined&&(!Number.isInteger(p[field])||p[field]<0||p[field]>(field==='focus'?25:field==='turn'?2:30)))fail(400,'Некорректное значение.');const changed=['stage','step','cursor'].some(k=>p[k]!==undefined&&p[k]!==l[k]);for(const k of ['stage','step','cursor','focus','turn'])if(p[k]!==undefined)l[k]=p[k];if(l.step>=counts[l.stage])l.step=0;if(changed){l.attempt++;l.reveal=false;l.showPeers=false;l.pairChosen=false}for(const k of ['reveal','showPeers'])if(typeof p[k]==='boolean')l[k]=p[k];}
 else if(url.pathname==='/api/answer'){if(m.role!=='student')fail(403,'Ответ отправляет ученица.');if(typeof b.text!=='string'||!b.text.trim()||b.text.length>1000)fail(400,'Ответ должен содержать от 1 до 1000 символов.');if(b.activity!==current(r)||b.attempt!==l.attempt)fail(409,'Задание изменилось. Обновите ответ.');if(r.answers.some(a=>a.memberId===m.id&&a.activity===current(r)&&a.attempt===l.attempt))fail(409,'Ответ уже отправлен. Преподаватель может дать повторную попытку.');if(l.stage===5&&l.step===1&&!l.pairChosen)fail(409,'Дождитесь выбора местоимения.');if(r.answers.length>=2000)fail(409,'Создайте новую комнату: лимит истории ответов достигнут.');if(l.stage===5&&l.step===1&&m.slot===l.cursor%2)fail(403,'Сейчас вы выбираете местоимение, партнёр выбирает форму.');r.answers.push({memberId:m.id,text:b.text.trim(),activity:current(r),attempt:l.attempt,time:Date.now()});}
 else if(url.pathname==='/api/pair-pick'){if(m.role!=='student'||l.stage!==5||l.step!==1||m.slot!==l.cursor%2)fail(403,'Сейчас местоимение выбирает другая ученица.');if(!Number.isInteger(b.index)||b.index<0||b.index>6)fail(400,'Неизвестное местоимение.');if(r.answers.some(a=>a.memberId===m.id&&a.activity===current(r)&&a.attempt===l.attempt))fail(409,'Выбор уже сделан.');l.focus=b.index;l.pairChosen=true;r.answers.push({memberId:m.id,text:['I','You','He','She','It','We','They'][b.index]+' — выбрано местоимение',activity:current(r),attempt:l.attempt,time:Date.now()});}
 else if(url.pathname==='/api/retry'){teacher(m);l.attempt++;l.reveal=false;l.showPeers=false;}
 else if(url.pathname==='/api/mark'){teacher(m);l.done[`${l.stage}-${l.step}`]=true;}
 else if(url.pathname==='/api/judge'){teacher(m);if(!['accepted','retry'].includes(b.verdict))fail(400,'Некорректная оценка.');const a=r.answers.find(a=>a.memberId===b.memberId&&a.activity===current(r)&&a.attempt===l.attempt);if(!a)fail(404,'Ответ не найден.');a.verdict=b.verdict;}
 else if(url.pathname==='/api/timer'){teacher(m);const now=Date.now();if(b.action==='start')l.timer={remaining:remaining(l.timer),startedAt:now};else if(b.action==='pause')l.timer={remaining:remaining(l.timer),startedAt:null};else if(b.action==='reset')l.timer={remaining:3600,startedAt:null};else fail(400,'Неизвестное действие таймера.');}
 else if(url.pathname==='/api/leave'){if(m.role!=='student')fail(403,'Преподаватель закрывает комнату.');r.members=r.members.filter(member=>member.id!==m.id);broadcast(r);json(res,200,{ok:true});for(const stream of clients.get(m.tokenHash)||[])stream.end();return}
 else if(url.pathname==='/api/close'){teacher(m);r.expiresAt=Date.now()-1;broadcast(r);json(res,200,{ok:true});for(const member of r.members)for(const stream of clients.get(member.tokenHash)||[])stream.end();return}
 else fail(404,'Действие не найдено.');broadcast(r);json(res,200,{room:snapshot(r,m)});return;
 }
 if(req.method!=='GET'&&req.method!=='HEAD')fail(405,'Метод не разрешён.');let pathname;try{pathname=decodeURIComponent(url.pathname)}catch{fail(400,'Некорректный адрес.')}const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep))fail(403,'Доступ запрещён.');const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'};fs.readFile(file,(err,data)=>{if(err){json(res,404,{error:'Файл не найден.'});return}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'self'"});res.end(req.method==='HEAD'?undefined:data)});
 }catch(e){if(!res.headersSent)json(res,e.status||500,{error:e.status?e.message:'Ошибка сервера. Попробуйте снова.'});else res.end();if(!e.status)console.error('Server error:',e.message)}});
server.listen(Number(process.env.PORT)||4174,process.env.HOST||'127.0.0.1',()=>console.log(`SPEAK UP! http://${process.env.HOST||'127.0.0.1'}:${process.env.PORT||4174}`));
