export const stages=[['THE ENGLISH ALPHABET','Алфавит',12],['FIRST READING','Первые слова',8],['PRONOUNS + TO BE','Базовая грамматика',12],['GRAMMAR PRACTICE','Практика',10],['READING & SPEAKING','Читаем и понимаем',10],['PAIR CHALLENGE + REVIEW','Говорим вместе',8]] as const;
export const steps=[['Алфавит A–Z','Найдите букву','Порядок букв','Соберите имя'],['Слова с картинками','Слово и картинка','Найдите слово','Соберите слово','Прочитайте вслух'],['Местоимения','Таблица to be','Примеры'],['Выберите форму','Соедините пары','Соберите предложение','Исправьте ошибку','Переведите','Опишите картинку'],['Словарь к тексту','Текст и формы to be','Понимание текста','True or False','Два предложения'],['Три предложения о себе','Парная игра','Памятка и домашнее задание']];
export const alphabet=[['A','/eɪ/','эй','apple','яблоко','apple'],['B','/biː/','би','bag','сумка','bag'],['C','/siː/','си','cat','кот','cat'],['D','/diː/','ди','dog','собака','dog'],['E','/iː/','и','egg','яйцо','egg'],['F','/ef/','эф','fish','рыба','fish'],['G','/dʒiː/','джи','girl','девочка','girl'],['H','/eɪtʃ/','эйч','hat','шляпа','hat'],['I','/aɪ/','ай','ice','лёд','ice'],['J','/dʒeɪ/','джей','jam','джем','jam'],['K','/keɪ/','кэй','key','ключ','key'],['L','/el/','эл','lion','лев','lion'],['M','/em/','эм','milk','молоко','milk'],['N','/en/','эн','nose','нос','nose'],['O','/əʊ/','оу','orange','апельсин','orange'],['P','/piː/','пи','pen','ручка','pen'],['Q','/kjuː/','кью','queen','королева','queen'],['R','/ɑː/','а:','red','красный','red'],['S','/es/','эс','sun','солнце','sun'],['T','/tiː/','ти','tea','чай','tea'],['U','/juː/','ю','umbrella','зонт','umbrella'],['V','/viː/','ви','van','фургон','van'],['W','/ˈdʌbəl.juː/','дабл-ю','window','окно','window'],['X','/eks/','экс','box','коробка; X в конце слова','box'],['Y','/waɪ/','уай','yellow','жёлтый','yellow'],['Z','/zed/','зэд','zebra','зебра','zebra']];
export const words=[['cat','кот','/kæt/','кэт'],['dog','собака','/dɒɡ/','дог'],['pen','ручка','/pen/','пэн'],['bag','сумка','/bæɡ/','бэг'],['map','карта','/mæp/','мэп'],['bed','кровать','/bed/','бэд'],['red','красный','/red/','рэд'],['big','большой','/bɪɡ/','биг'],['milk','молоко','/mɪlk/','милк'],['sun','солнце','/sʌn/','сан']];
export const pronouns=[['I','я','am','I am Anna.','Я Анна.','girl'],['You','ты / вы','are','You are happy.','Ты счастлива.','happy'],['He','он','is','He is a student.','Он студент.','boy'],['She','она','is','She is a teacher.','Она учительница.','teacher'],['It','оно / это','is','It is a cat.','Это кот.','cat'],['We','мы','are','We are friends.','Мы друзья.','friends'],['They','они','are','They are students.','Они студенты.','students']];
export const vocabulary=[['student','студент / ученица','student'],['teacher','учитель / учительница','teacher'],['friend','друг / подруга','friends'],['happy','счастливый / счастливая','happy'],['from','из / откуда','map'],['name','имя','name']];
export const textSentences=['Hi!','My name is Mia.','I am a student.','I am from Italy.','My friend is Emma.','She is a student too.','We are friends.','We are happy.'];
export const translation=['Привет!','Меня зовут Mia.','Я ученица.','Я из Италии.','Моя подруга — Emma.','Она тоже ученица.','Мы подруги.','Мы счастливы.'];
export type Question={q:string;options:string[];answer:string;why:string;art?:string};
export const quizzes:Record<string,Question[]>={
 '0-1':[{q:'Найдите букву с британским названием /zed/.',options:['Z','S','C'],answer:'Z',why:'Z /zed/ — зэд.'},{q:'Какая заглавная буква соответствует маленькой r?',options:['P','R','B'],answer:'R',why:'R r — /ɑː/.'},{q:'Найдите букву O.',options:['Q','O','D'],answer:'O',why:'O /əʊ/ — название буквы; не правило чтения каждого слова.'}],
 '0-2':[{q:'A, B, __, D',options:['C','E','G'],answer:'C',why:'A, B, C, D.'},{q:'L, M, __, O',options:['N','P','I'],answer:'N',why:'L, M, N, O.'},{q:'W, X, __, Z',options:['V','Y','U'],answer:'Y',why:'W, X, Y, Z.'}],
 '1-2':[{q:'Какое слово называет предмет на картинке?',art:'pen',options:['pen','pan','pin'],answer:'pen',why:'pen — ручка. Прочитайте с преподавателем.'},{q:'Найдите слово «сумка».',art:'bag',options:['big','bag','bed'],answer:'bag',why:'bag /bæɡ/ — сумка.'},{q:'Найдите слово «молоко».',art:'milk',options:['map','milk','silk'],answer:'milk',why:'milk /mɪlk/ — молоко.'}],
 '3-0':[{q:'She ___ a student.',options:['am','is','are'],answer:'is',why:'She + is. Она ученица.',art:'student'},{q:'I ___ happy.',options:['is','are','am'],answer:'am',why:'I + am. Я счастлива.',art:'happy'},{q:'You ___ a teacher.',options:['are','am','is'],answer:'are',why:'You + are. Ты учительница.',art:'teacher'},{q:'It ___ a cat.',options:['are','is','am'],answer:'is',why:'It + is. Это кот.',art:'cat'}],
 '3-3':[{q:'Исправьте: They is friends.',options:['They are friends.','They am friends.','They is friend.'],answer:'They are friends.',why:'They требует are; friends — друзья.',art:'friends'},{q:'Исправьте: He are a student.',options:['He am a student.','He is a student.','He are students.'],answer:'He is a student.',why:'He требует is. A student — один студент.',art:'boy'}],
 '4-2':[{q:'Who is Mia? — Кто Mia?',options:['A student','A teacher','A cat'],answer:'A student',why:'В тексте: I am a student.'},{q:'Where is Mia from? — Откуда Mia?',options:['France','Italy','Russia'],answer:'Italy',why:'В тексте: I am from Italy.'},{q:'Who is Emma? — Кто Emma?',options:["Mia's friend",'A teacher','A dog'],answer:"Mia's friend",why:'My friend is Emma. She is a student too.'},{q:'Are Mia and Emma friends? — Mia и Emma подруги?',options:['Yes','No'],answer:'Yes',why:'We are friends. Здесь достаточно короткого Yes.'}],
 '4-3':[{q:'Mia is a teacher.',options:['True — верно','False — неверно'],answer:'False — неверно',why:'Mia — ученица, не учительница.'},{q:'Emma is a student too.',options:['True — верно','False — неверно'],answer:'True — верно',why:'В тексте: She is a student too.'},{q:'Mia and Emma are happy.',options:['True — верно','False — неверно'],answer:'True — верно',why:'We are happy.'}]
};
export const builds:Record<string,string[][]>={'0-3':[['A','N','N','A'],['M','I','A'],['E','M','M','A']],'1-3':[['c','a','t'],['d','o','g'],['p','e','n']],'3-2':[['She','is','happy.'],['I','am','a','student.'],['We','are','friends.']]};
export const writing:Record<string,{q:string;accepted?:string[];hint:string;art?:string}[]>={
 '3-4':[{q:'Переведите: «Я студентка».',accepted:['I am a student.',"I'm a student."],hint:'I am a student. / I’m a student.',art:'student'},{q:'Переведите: «Она счастлива».',accepted:['She is happy.',"She's happy."],hint:'She is happy. / She’s happy.',art:'happy'},{q:'Переведите: «Мы друзья».',accepted:['We are friends.',"We're friends."],hint:'We are friends. / We’re friends.',art:'friends'}],
 '3-5':[{q:'Опишите персонажа. Начните с He is…',hint:'Например: He is a student. He is happy. Оценивает преподаватель.',art:'boy'},{q:'Опишите персонажа. Начните с She is…',hint:'Например: She is a teacher. She is happy. Оценивает преподаватель.',art:'teacher'}],
 '4-4':[{q:'Напишите два предложения о Mia и Emma по тексту.',hint:'Например: Mia is a student. Emma is a student too. Возможны другие верные факты. Проверяет преподаватель.'}],
 '5-0':[{q:'Составьте 3 предложения о себе или вымышленном персонаже.',hint:'My name is…\nI am a student. / I am a teacher. / I am happy.\nI am from…'}]
};
export const teacher=[
 ['Названия 26 букв; различие буквы и звука.','Название буквы нужно для алфавита и spelling. В cat буква A даёт /æ/, а не своё название /eɪ/. Русская подсказка приблизительна. Z /zed/, R /ɑː/, O /əʊ/.','Найдите букву в сетке; назовите буквы имени по очереди.','Найти: Z, R, O. Последовательности: C, N, Y. Имена: ANNA, MIA, EMMA.','Не переносить названия букв в чтение слов. X показана в конце box.','Найдите первую букву имени партнёрши.'],
 ['Прочитать десять слов с помощью преподавателя.','Читаем вместе. Знание алфавита не означает знание правил чтения. IPA точнее русской записи. Преподаватель произносит слова по видеосвязи.','Найдите, соберите и прочитайте слово.','cat, dog, pen, bag, map, bed, red, big, milk, sun. Выбор: pen, bag, milk. Сборка: cat, dog, pen.','Не требовать угадывания звуков; /æ/ не равно русскому э, /ʌ/ не равно русскому а.','Сравните bag и big, помогите прочитать.'],
 ['Связать местоимения с am/is/are.','Am/is/are — формы to be. По-русски «Я Анна», по-английски I am Anna. A student/a teacher пока учим как готовые сочетания.','Кого заменяет She? Какая форма после I? После We?','I am; You are; He/She/It is; We/They are. Примеры на экране.','Не пропускать глагол. Не вводим отрицания, общие вопросы, Present Simple.','Замените Anna на She в готовом примере.'],
 ['Применить три формы в разных заданиях.','Ученица 1: первые вопросы Choose и первая сборка. Ученица 2: следующие вопросы и вторая сборка. Вместе: пары и исправления. Переводы выполняют по очереди.','Почему She is? Исправьте They is friends. Опишите персонажа.','Choose: is, am, are, is. Match: I→am, He→is, They→are. Fix: They are friends; He is a student.','I’m, She’s, We’re допустимы. Иные корректные варианты можно принять вручную.','Каждая описывает новую картинку известными словами.'],
 ['Понять текст и найти формы to be.','Сначала словарь, затем читаем по предложениям. Too — тоже. Грамматику вопросов не разбираем. В Are… friends? разрешите Yes/No.','Who is Mia? Where is Mia from? Who is Emma? Are they friends?','A student; Italy; Mia’s friend; Yes. True/False: False, True, True. Все формы to be выделяются на экране.','Emma — тоже ученица. Не требовать полного ответа с новой вопросительной конструкцией.','Назовите два факта без перевода текста.'],
 ['Прочитать три собственных предложения и повторить материал.','Каждая пишет три фразы и читает партнёру. Страну и описание можно выдумать. В игре первая выбирает местоимение, вторая форму; затем наоборот.','Прочитайте фразы друг другу. Что подходит после They?','I am; You/We/They are; He/She/It is. Домашние пропуски: am, is, are, is, are.','Личные данные не обязательны. Другие верные описания принимайте вручную.','Повторите игру с новыми местоимениями.']
];
export function activitySize(stage:number,step:number){const key=`${stage}-${step}`;return quizzes[key]?.length||builds[key]?.length||writing[key]?.length||(stage===1&&step===4?words.length:stage===5&&step===1?2:1);}
