import {useEffect,useState} from 'react';
export type Lesson={stage:number;step:number;cursor:number;focus:number;turn:number;done:Record<string,boolean>;reveal:boolean;showPeers:boolean;pairChosen:boolean;attempt:number;timer:{remaining:number;startedAt:number|null}};
export type Member={id:string;name:string;avatar:number;role:'teacher'|'student';slot:number;connected:boolean};
export type Answer={memberId:string;text:string;attempt:number;activity:string;time:number;verdict?:'accepted'|'retry'};
export type Room={code:string;lesson:Lesson;members:Member[];me:Member;answers:Answer[];revision:number;serverTime:number;clockOffset?:number};
export type Credential={token:string;code:string};
export const newLesson=():Lesson=>({stage:0,step:0,cursor:0,focus:0,turn:0,done:{},reveal:false,showPeers:false,pairChosen:false,attempt:0,timer:{remaining:3600,startedAt:null}});
export const roomsAvailable=import.meta.env.MODE !== 'github-pages';
const credentialKey='sonya-room-credential-v2';
export function useRoom(){const [credential,setCredential]=useState<Credential|null>(()=>{try{if(!roomsAvailable)return null;return JSON.parse(localStorage.getItem(credentialKey)||'null')}catch{return null}}),[room,setRoom]=useState<Room|null>(null),[status,setStatus]=useState('Локальный режим'),[error,setError]=useState('');
 useEffect(()=>{if(!roomsAvailable)return;if(credential)localStorage.setItem(credentialKey,JSON.stringify(credential));else localStorage.removeItem(credentialKey)},[credential]);
 async function api(action:string,body:unknown,token=credential?.token){if(!roomsAvailable)throw Error('Учебные комнаты требуют отдельного сервера.');if(location.protocol==='file:')throw Error('Комнаты работают через сервер. Запустите «Открыть урок.cmd» и откройте адрес localhost.');const res=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});let data;try{data=await res.json()}catch{throw Error('Backend недоступен. Локальный урок работает; запустите node server.cjs.')}if(!res.ok)throw Error(data.error||'Ошибка сервера');return data;}
 useEffect(()=>{if(!credential)return;let stopped=false;let controller:AbortController|null=null;let retry:ReturnType<typeof setTimeout>;async function connect(){controller=new AbortController();setStatus('Подключение…');try{const res=await fetch('/api/events',{headers:{Authorization:'Bearer '+credential!.token},signal:controller.signal});if(!res.ok){if(res.status===401||res.status===410){setError('Комната закончена или доступ истёк. Можно создать новую комнату.');setCredential(null);setRoom(null);return}throw Error('Сервер временно недоступен');}setStatus('Подключено');setError('');const reader=res.body!.getReader(),decoder=new TextDecoder();let buffer='';while(!stopped){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let end;while((end=buffer.indexOf('\n\n'))>=0){const event=buffer.slice(0,end);buffer=buffer.slice(end+2);if(event.startsWith('data: ')){const snapshot=JSON.parse(event.slice(6));setRoom({...snapshot,clockOffset:snapshot.serverTime-Date.now()});setStatus('Подключено');}}}if(!stopped)throw Error('Связь прервана');}catch(e){if(stopped)return;setStatus('Переподключение…');setError('Связь прервана. Состояние восстановится после подключения.');retry=setTimeout(connect,1500);}}connect();return()=>{stopped=true;controller?.abort();clearTimeout(retry)}},[credential]);
 async function create(name:string){try{const data=await api('create',{name});setCredential(data.credential);setRoom({...data.room,clockOffset:data.room.serverTime-Date.now()});setError('')}catch(e){setError((e as Error).message)}}
 async function join(code:string,name:string,avatar:number){try{const data=await api('join',{code,name,avatar});setCredential(data.credential);setRoom({...data.room,clockOffset:data.room.serverTime-Date.now()});setError('')}catch(e){setError((e as Error).message)}}
 async function action(action:string,body:unknown={}){try{const data=await api(action,body);if(data.room)setRoom({...data.room,clockOffset:data.room.serverTime-Date.now()});setError('');return true}catch(e){setError((e as Error).message);return false}}
 function leave(){setCredential(null);setRoom(null);setStatus('Локальный режим');setError('')}
 return {room,credential,status,error,create,join,action,leave};
}
